// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wayfinder.DataLayer.DataContext;

#nullable disable

namespace Wayfinder.DataLayer.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.AuthUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AuthUsers");
                });

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "itadori.yuji@jjk.com",
                            FirstName = "Yuji",
                            IsActive = true,
                            LastName = "Itadori",
                            PhoneNumber = "1000000001",
                            UpdatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "itadori"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "megumi.fushiguro@jjk.com",
                            FirstName = "Megumi",
                            IsActive = true,
                            LastName = "Fushiguro",
                            PhoneNumber = "1000000002",
                            UpdatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "fushiguro"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nobara.kugisaki@jjk.com",
                            FirstName = "Nobara",
                            IsActive = false,
                            LastName = "Kugisaki",
                            PhoneNumber = "1000000003",
                            UpdatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "kugisaki"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "satoru.gojo@jjk.com",
                            FirstName = "Satoru",
                            IsActive = true,
                            LastName = "Gojo",
                            PhoneNumber = "1000000004",
                            UpdatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "gojo"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kento.nanami@jjk.com",
                            FirstName = "Kento",
                            IsActive = false,
                            LastName = "Nanami",
                            PhoneNumber = "1000000005",
                            UpdatedAt = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "nanami"
                        });
                });

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.AuthUserEntity", b =>
                {
                    b.HasOne("Wayfinder.DataLayer.Entity.UserEntity", "User")
                        .WithOne("AuthUser")
                        .HasForeignKey("Wayfinder.DataLayer.Entity.AuthUserEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.RefreshTokenEntity", b =>
                {
                    b.HasOne("Wayfinder.DataLayer.Entity.UserEntity", "User")
                        .WithMany("RefreshToken")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wayfinder.DataLayer.Entity.UserEntity", b =>
                {
                    b.Navigation("AuthUser")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
